version: '2.4'

include:
  - path:
    - ../config/docker-compose-common-services.yaml
    - docker-compose-override.yaml

services:

  repo-converter:
    container_name: repo-converter
    image: ghcr.io/sourcegraph/implementation-bridge-repo-converter:latest@sha256:805a33589b977fd07e29887d9346a973b3e214d444dc739be09ebb47740b7f72
    volumes:
      - ../config/repos-to-convert.yaml:/sourcegraph/repos-to-convert.yaml:ro
      - ../config/toprc:/root/.config/procps/toprc
      - ../src-serve-root/:/sourcegraph/src-serve-root
    restart: always
    environment:
      - REPO_CONVERTER_INTERVAL_SECONDS=900
      # - LOG_LEVEL=DEBUG # DEBUG INFO WARNING ERROR CRITICAL # Default is INFO if unspecified
